# Generated by Django 4.0.4 on 2024-06-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture_url',
            field=models.ImageField(default='2placeholder_test_b9l9NT5.png', upload_to='profile_images'),
        ),
    ]
