# Generated by Django 4.0.4 on 2024-05-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_count',
            field=models.FloatField(default=0),
        ),
    ]
