# Generated by Django 4.0.4 on 2024-06-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
