# Generated by Django 4.0.4 on 2024-06-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order_order_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_type',
            new_name='order_status',
        ),
    ]
